# Generated by Django 5.0.9 on 2026-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='evt_type_ts_idx')],
            },
        ),
    ]
